services:
  freescout:
    image: tiredofit/freescout:latest
    platform: linux/amd64
    environment:
      - DEBUG_MODE=FALSE
  payment-backend:
    build:
      context: ./payment-backend
    ports:
      - "3000:80"
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}
