services:
  freescout:
    image: tiredofit/freescout:latest-arm32v7
    container_name: freescout
    ports:
      - "8080:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - ./data/freescout:/data

  payment-backend:
    build:
      context: ./payment-backend
    ports:
      - "3000:80"
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:3306/${DB_NAME}
